version: '3.8'

networks:
  server-connection:
    driver: bridge

services:
  nginx:
    container_name: web_server
    build:
      context: ./nginx
    ports:
      - 80:80
    networks:
      - server-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - app_server

  app_server:
    container_name: was
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    networks:
      - server-connection
    environment:
      - NODE_ENV=dev
    env_file:
      - ./.dev.env
