version: '3.8'

networks:
  server-connection:
    driver: bridge

services:
  nginx:
    container_name: web_server
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - server-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - app_server

  app_server:
    container_name: was
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - '8080'
    networks:
      - server-connection
    environment:
      - NODE_ENV=dev
    env_file:
      - ./.env
